name: Functional Issue Report
description: Report a clear functional error, such as a button not working or a logic bug
title: "Title: Please briefly describe the issue"
labels: [enhancement, question, documentation, invalid, bug, help wanted, functional]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your submission! Please make sure you're reporting a **functional issue**, not a performance concern, UI feedback, or personal suggestion.

  - type: dropdown
    id: issue-type
    attributes:
      label: Type of Issue
      description: Please select the type of problem you're reporting
      options:
        - Functional (F): Functional error such as logic bugs or non-working buttons
        - Non-Functional (NF): UI/UX issues, slowness, suggestions etc. ❌ Please do NOT submit here
      default: 0
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Runtime Environment
      description: Provide your browser, OS, and version
      placeholder: e.g. Chrome 123 / macOS 14.4
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue
      placeholder: |
        1. Open the page
        2. Click button X
        3. Problem Y occurs
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior (at least 50 EN characters, too short may be auto-rejected by AI)
      description: Describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior (attach screenshot, at least 50 EN characters, too short may be auto-rejected by AI)
      description: Describe what actually happened (attach screenshot)
    validations:
      required: true

  - type: checkboxes
    id: confirmations
    attributes:
      label: Submission Confirmation (If you’re sure this is a bug, you can add the 'BUG' label)
      options:
        - label: I confirm this is a functional issue, not a suggestion or non-functional feedback
          required: true
        - label: I acknowledge and agree that the final interpretation and handling (e.g. Close, mark as invalid) of this issue lies with the project contributors and maintainers
          required: true
