name: ⚠Сообщение о функциональной проблеме
description: Сообщите о чёткой функциональной ошибке, например, неработающей кнопке или сбое в логике
title: "Заголовок: кратко опишите проблему"
labels: [enhancement, question, documentation, invalid, help wanted, functional]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за ваше сообщение! Убедитесь, что вы сообщаете именно о **функциональной проблеме**, а не об общей производительности, удобстве или субъективных предложениях.

  - type: dropdown
    id: issue-type
    attributes:
      label: Тип проблемы
      description: Пожалуйста, выберите тип ошибки
      options:
        - "Функциональная (F): Ошибки логики, неработающие кнопки и т.п."
        - "Нефункциональная (NF): UI-проблемы, медленная работа, предложения и т.д. ❌ Не отправлять здесь"
      default: 0
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Окружение
      description: Укажите ваш браузер, операционную систему и версию
      placeholder: "Chrome 123 / macOS 14.4"
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Шаги для воспроизведения
      placeholder: |
        1. Откройте страницу
        2. Нажмите кнопку X
        3. Произошла ошибка Y
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Ожидаемое поведение (минимум 30 символов)
    validations:
      required: true
      maxLength: 200

  - type: textarea
    id: actual-behavior
    attributes:
      label: Фактическое поведение (с приложением скриншота)
    validations:
      required: true

  - type: checkboxes
    id: confirmations
    attributes:
      label: Подтверждение отправки
      options:
        - label: "Я подтверждаю, что это функциональная проблема"
          required: true
        - label: "Я согласен с политикой обработки issue"
          required: true
